### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by nevrome** [peterhurford/checkr#34]
Any plans to make a CRAN release?

**Comment by peterhurford** [comment]
Hi @nevrome , thanks for your interest. Long-term I'd like to submit to CRAN, however checkr still has some bugs I'd like fixed first. Unfortunately, R programming is not currently a priority for me.

**Comment by nevrome** [comment]
Very sad. Without a CRAN release I can't consider to use it for packages that are ultimately intended to be released. 

Nevertheless thanks for the effort! I'm looking forward to the moment when this project again becomes a priority for you.

**Comment by peterhurford** [comment]
@nevrome Sorry! 😢 

It really means a lot to me that you've voiced your support for this project, though, and that really does motivate me a lot to eventually come back to it. I'll put this at the top of my R backlog for whenever I come back to R.

I can ping you on this issue when development resumes in earnest. :)

**Comment by nevrome** [comment]
Sounds create! You can contact me if you need somebody for testing or minor bugfixing.

**Comment by peterhurford** [comment]
Hi @nevrome. I've have an interest in getting stuff on CRAN now -- I now have three packages on there. It also looks like @rmsharp is interested in getting this on CRAN. So I'm greenlighting this project. ;) 👍 💚 

I made a milestone to track what I feel needs to be done to get this on CRAN. I will try to work on it and I encourage other people to help out where they can. 👍  https://github.com/peterhurford/checkr/milestone/1

**Comment by rmsharp** [comment]
Peter,

It looks like a little bit of syntactic sugar with roxugen2 @param and @return could populate the ensure function with pre and post values. I expect you or Clemens Schmid would know if that is correct and how hard it would be.

Mark
R. Mark Sharp
7526 Meadow Green St.
San Antonio, TX 78251
mobile: 210-218-2868
rmsharp@me.com

**Comment by rmsharp** [comment]
I should have said “with regard to class checking”. It would not address domain testing.

Mark
R. Mark Sharp
7526 Meadow Green St.
San Antonio, TX 78251
mobile: 210-218-2868
rmsharp@me.com

**Comment by nevrome** [comment]
@rmsharp 

I think you should open a new issue for this. 

AFAIK there's no generally agreed upon way how to describe object types in the roxygen tags. Therefore it's not practical to set this up. But maybe I don't understand your idea correctly.

**Comment by rmsharp** [comment]
It was simply an off the cuff comment because of the redundant information in the first example code. I do like the documentation to include the data types, but I do not like having multiple sources that can get out of sync. In this case the code inside the call to ensure() is obviously the authoritative source.

#' @param x numeric. The number to add.
#' @param y numeric. The number to add.
add <-
 ensure(
  pre = list(x %is% numeric, y %is% numeric),
  post = result %is% numeric,  # `result` matches whatever the function returns.
  function(x, y) x + y
)


R. Mark Sharp
7526 Meadow Green St.
San Antonio, TX 78251
mobile: 210-218-2868
rmsharp@me.com
